// Rubricas de nota (0-5) por dimensão de cada bloco, transcritas literalmente
// da seção "CRITÉRIOS DE SCORE" de cada bloco na especificação técnica da
// Andréa ("BLINDADOKP_NEGÓCIO_ATUAL"). Usadas pelo motor de IA de
// pontuação (src/diagnostic/ai/scoreBlocks.js) como o texto de referência
// que a IA deve usar para avaliar as respostas — a IA não decide os
// critérios, só aplica os critérios já dados aqui.
//
// Os Blocos 1 (Negócio Atual) e 4 (Diferenciação) não têm seção de
// critérios de nota (0-5) detalhada na especificação — só os nomes das
// dimensões, sem o texto de cada nível. Por isso não têm rubrica aqui e
// ficam de fora do motor de pontuação (block_score = null), em vez de
// inventar critérios que a Andréa não escreveu.

const SCORE_RUBRICS = {
  audience: {
    name: 'Público e Cliente Ideal',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'audience_clarity_score',
        label: 'Clareza do público',
        criteria: {
          0: 'não consegue identificar',
          1: '"qualquer pessoa"',
          2: 'público muito amplo',
          3: 'perfil razoavelmente identificado',
          4: 'perfil claro',
          5: 'perfil específico e sustentado por informações',
        },
      },
      {
        field: 'problem_relevance_score',
        label: 'Relevância do problema',
        criteria: {
          0: 'problema indefinido',
          1: 'pouco relevante',
          2: 'incômodo moderado',
          3: 'problema relevante',
          4: 'forte',
          5: 'problema central e altamente valorizado',
        },
      },
      {
        field: 'urgency_score',
        label: 'Urgência da demanda',
        criteria: {
          0: 'nenhuma',
          1: 'baixa',
          2: 'moderada',
          3: 'intenção real de resolver',
          4: 'busca ativa',
          5: 'necessidade imediata',
        },
      },
      {
        field: 'professional_fit_score',
        label: 'Aderência ao profissional',
        criteria: {
          0: 'incompatível',
          1: 'baixa',
          2: 'parcial',
          3: 'boa',
          4: 'muito boa',
          5: 'forte especialização/experiência',
        },
      },
      {
        field: 'economic_viability_score',
        label: 'Viabilidade econômica potencial',
        criteria: {
          0: 'incompatibilidade clara',
          1: 'muito baixa',
          2: 'baixa',
          3: 'potencial adequado',
          4: 'boa',
          5: 'forte potencial',
        },
        note: 'Seja conservadora aqui — o Bloco de Precificação vai detalhar melhor a viabilidade econômica.',
      },
      {
        field: 'priority_focus_score',
        label: 'Clareza de prioridade',
        criteria: {
          0: 'nenhum foco',
          1: 'vários públicos sem direção',
          2: 'preferência fraca',
          3: 'público prioritário identificado',
          4: 'prioridade justificada',
          5: 'prioridade clara e coerente com demanda + expertise + negócio',
        },
      },
    ],
  },

  positioning: {
    name: 'Posicionamento',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'positioning_clarity_score',
        label: 'Clareza',
        criteria: {
          0: 'impossível entender',
          1: 'muito confuso',
          2: 'parcialmente compreensível',
          3: 'claro',
          4: 'muito claro',
          5: 'claro imediatamente',
        },
      },
      {
        field: 'positioning_specificity_score',
        label: 'Especificidade',
        criteria: {
          0: 'extremamente genérico',
          1: 'genérico',
          2: 'alguma especificidade',
          3: 'bem direcionado',
          4: 'específico',
          5: 'altamente específico e memorável',
        },
      },
      {
        field: 'audience_alignment_score',
        label: 'Aderência ao público',
        criteria: {
          0: 'desalinhado',
          1: 'muito baixa',
          2: 'parcial',
          3: 'boa',
          4: 'muito boa',
          5: 'totalmente coerente com o público prioritário',
        },
      },
      {
        field: 'authority_score',
        label: 'Autoridade percebida',
        criteria: {
          0: 'expertise invisível',
          1: 'muito fraca',
          2: 'pouco percebida',
          3: 'adequada',
          4: 'forte',
          5: 'autoridade claramente percebida',
        },
      },
      {
        field: 'price_alignment_score',
        label: 'Coerência com valor/ticket',
        criteria: {
          0: 'posicionamento incompatível',
          1: 'muito fraco',
          2: 'pouco sustentado',
          3: 'adequado',
          4: 'forte',
          5: 'sustenta claramente percepção premium',
        },
      },
      {
        field: 'positioning_territory_score',
        label: 'Força do território de posicionamento',
        criteria: {
          0: 'inexistente',
          1: 'totalmente genérico',
          2: 'pouco definido',
          3: 'identificável',
          4: 'forte',
          5: 'claro, específico e potencialmente proprietário',
        },
      },
    ],
  },

  offer: {
    name: 'Oferta',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'offer_clarity_score',
        label: 'Clareza da oferta',
        criteria: {
          0: 'impossível entender',
          1: 'muito confusa',
          2: 'parcialmente clara',
          3: 'compreensível',
          4: 'clara',
          5: 'extremamente clara',
        },
      },
      {
        field: 'offer_audience_fit_score',
        label: 'Aderência ao público',
        criteria: {
          0: 'incompatível',
          1: 'baixa',
          2: 'parcial',
          3: 'boa',
          4: 'muito boa',
          5: 'criada especificamente para o público',
        },
      },
      {
        field: 'problem_relevance_score',
        label: 'Relevância do problema',
        criteria: {
          0: 'problema inexistente/irrelevante',
          1: 'fraco',
          2: 'moderado',
          3: 'relevante',
          4: 'importante',
          5: 'altamente valorizado',
        },
      },
      {
        field: 'transformation_desirability_score',
        label: 'Desejabilidade da transformação',
        criteria: {
          0: 'vaga',
          1: 'pouco desejável',
          2: 'moderada',
          3: 'interessante',
          4: 'forte',
          5: 'muito forte e clara',
        },
      },
      {
        field: 'offer_differentiation_score',
        label: 'Diferenciação',
        criteria: {
          0: 'commodity',
          1: 'igual à maioria',
          2: 'pequenas diferenças',
          3: 'diferenciação clara',
          4: 'forte',
          5: 'difícil de comparar diretamente',
        },
      },
      {
        field: 'deliverable_coherence_score',
        label: 'Coerência dos entregáveis',
        criteria: {
          0: 'desorganizados',
          1: 'excesso sem função',
          2: 'parcialmente coerentes',
          3: 'adequados',
          4: 'muito coerentes',
          5: 'cada elemento está diretamente ligado ao resultado',
        },
      },
      {
        field: 'perceived_value_score',
        label: 'Valor percebido',
        criteria: {
          0: 'muito baixo',
          1: 'baixo',
          2: 'insuficiente',
          3: 'adequado',
          4: 'alto',
          5: 'muito alto',
        },
      },
    ],
  },

  pricing: {
    name: 'Precificação e Monetização',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'pricing_clarity_score',
        label: 'Clareza da precificação',
        criteria: {
          0: 'preço aleatório',
          1: 'sem critério consistente',
          2: 'baseado principalmente em concorrência/tempo',
          3: 'considera alguns fatores estratégicos',
          4: 'considera custo + público + valor',
          5: 'método estruturado e revisado por dados',
        },
      },
      {
        field: 'economic_sustainability_score',
        label: 'Sustentabilidade econômica',
        criteria: {
          0: 'provável prejuízo',
          1: 'muito frágil',
          2: 'baixa sustentabilidade',
          3: 'funcional',
          4: 'saudável',
          5: 'altamente sustentável',
        },
      },
      {
        field: 'margin_score',
        label: 'Margem',
        criteria: {
          0: 'negativa',
          1: 'crítica',
          2: 'baixa',
          3: 'adequada',
          4: 'boa',
          5: 'muito boa',
        },
        note: 'Se a cliente não sabe os custos de entrega (delivery_cost_awareness never_calculated/dont_know), retorne null — nunca invente a margem.',
      },
      {
        field: 'price_value_alignment_score',
        label: 'Coerência preço-valor',
        criteria: {
          0: 'incompatível',
          1: 'muito fraca',
          2: 'pouco sustentada',
          3: 'adequada',
          4: 'forte',
          5: 'valor percebido sustenta claramente o ticket',
        },
      },
      {
        field: 'delivery_efficiency_score',
        label: 'Eficiência da entrega',
        criteria: {
          0: 'extremamente dependente de horas',
          1: 'muito pesada',
          2: 'pesada',
          3: 'funcional',
          4: 'eficiente',
          5: 'altamente alavancada',
        },
      },
      {
        field: 'audience_price_fit_score',
        label: 'Adequação ao público',
        criteria: {
          0: 'incompatível',
          1: 'muito baixa',
          2: 'baixa',
          3: 'adequada',
          4: 'boa',
          5: 'forte aderência econômica',
        },
      },
      {
        field: 'continuity_potential_score',
        label: 'Potencial de continuidade',
        criteria: {
          0: 'nenhuma necessidade posterior',
          1: 'muito baixa',
          2: 'oportunidade incerta',
          3: 'necessidade identificável',
          4: 'continuidade clara',
          5: 'modelo estruturado de renovação/recorrência',
        },
      },
    ],
  },

  communication: {
    name: 'Comunicação e Conteúdo',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'message_clarity_score',
        label: 'Clareza da mensagem',
        criteria: {
          0: 'comunicação confusa',
          1: 'muito genérica',
          2: 'parcialmente clara',
          3: 'compreensível',
          4: 'clara',
          5: 'imediatamente clara e coerente',
        },
      },
      {
        field: 'communication_consistency_score',
        label: 'Consistência',
        criteria: {
          0: 'praticamente inexistente',
          1: 'muito irregular',
          2: 'irregular',
          3: 'razoável',
          4: 'consistente',
          5: 'consistente e sustentável',
        },
      },
      {
        field: 'authority_communication_score',
        label: 'Autoridade',
        criteria: {
          0: 'expertise invisível',
          1: 'fraca',
          2: 'pouco percebida',
          3: 'adequada',
          4: 'forte',
          5: 'autoridade claramente construída',
        },
      },
      {
        field: 'audience_communication_fit_score',
        label: 'Aderência ao público',
        criteria: {
          0: 'desalinhada',
          1: 'baixa',
          2: 'parcial',
          3: 'adequada',
          4: 'forte',
          5: 'comunicação altamente relevante para o público prioritário',
        },
      },
      {
        field: 'content_conversion_score',
        label: 'Capacidade de conversão',
        criteria: {
          0: 'nenhuma próxima ação',
          1: 'muito fraca',
          2: 'ocasional',
          3: 'funcional',
          4: 'clara',
          5: 'caminho consistente entre conteúdo e oportunidade comercial',
        },
      },
      {
        field: 'production_efficiency_score',
        label: 'Eficiência de produção',
        criteria: {
          0: 'produção extremamente pesada',
          1: 'muito ineficiente',
          2: 'difícil de sustentar',
          3: 'funcional',
          4: 'eficiente',
          5: 'sistema organizado e reutilizável',
        },
      },
      {
        field: 'professional_communication_safety_score',
        label: 'Segurança na comunicação profissional',
        criteria: {
          0: 'alto risco percebido ou desconhecimento',
          1: 'muita insegurança',
          2: 'insegurança relevante',
          3: 'conhecimento básico',
          4: 'boa estrutura de revisão',
          5: 'comunicação estruturada com critérios e revisão adequados',
        },
        note: 'Esta nota será refinada com dados do Bloco 13 (Ética) quando disponível — aqui é uma primeira estimativa.',
      },
    ],
  },

  acquisition: {
    name: 'Marketing e Aquisição',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'channel_clarity_score',
        label: 'Clareza dos canais',
        criteria: {
          0: 'não sabe de onde vêm clientes',
          1: 'pouca clareza',
          2: 'percepção informal',
          3: 'principais canais conhecidos',
          4: 'canais claramente identificados',
          5: 'origem e desempenho acompanhados',
        },
      },
      {
        field: 'acquisition_predictability_score',
        label: 'Previsibilidade',
        criteria: {
          0: 'aquisição totalmente imprevisível',
          1: 'muito instável',
          2: 'irregular',
          3: 'alguma constância',
          4: 'previsível',
          5: 'sistema consistente de geração de oportunidades',
        },
      },
      {
        field: 'channel_diversification_score',
        label: 'Diversificação',
        criteria: {
          0: 'nenhuma fonte consistente',
          1: 'dependência total de uma fonte frágil',
          2: 'dependência alta',
          3: 'alguma diversificação',
          4: 'combinação saudável',
          5: 'fontes diversificadas e monitoradas',
        },
        note: 'Não penalize automaticamente um único canal caso ele seja eficiente, previsível e sustentável.',
      },
      {
        field: 'funnel_maturity_score',
        label: 'Estrutura do funil',
        criteria: {
          0: 'inexistente',
          1: 'totalmente improvisado',
          2: 'pouco definido',
          3: 'caminho básico existente',
          4: 'estruturado',
          5: 'estruturado, acompanhado e otimizado',
        },
      },
      {
        field: 'acquisition_measurement_score',
        label: 'Mensuração',
        criteria: {
          0: 'nenhum dado',
          1: 'quase nenhum',
          2: 'métricas isoladas',
          3: 'acompanha alguns indicadores',
          4: 'boa mensuração',
          5: 'aquisição ligada a leads, vendas e custo',
        },
      },
      {
        field: 'demand_conversion_score',
        label: 'Conversão da demanda',
        criteria: {
          0: 'interesse praticamente não avança',
          1: 'muito baixa',
          2: 'baixa',
          3: 'funcional',
          4: 'boa',
          5: 'forte',
        },
        note: 'Esta nota será refinada com dados do Bloco 9 (Vendas e Conversão) quando disponível.',
      },
      {
        field: 'scaling_readiness_score',
        label: 'Prontidão para escala',
        criteria: {
          0: 'não preparado',
          1: 'muitos gargalos prévios',
          2: 'estrutura frágil',
          3: 'pode testar crescimento',
          4: 'preparado',
          5: 'oferta + operação + vendas + tracking preparados para escalar',
        },
      },
    ],
  },

  sales: {
    name: 'Vendas e Conversão',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'sales_process_clarity_score',
        label: 'Clareza do processo comercial',
        criteria: {
          0: 'inexistente',
          1: 'totalmente improvisado',
          2: 'pouco definido',
          3: 'processo básico',
          4: 'estruturado',
          5: 'estruturado, acompanhado e otimizado',
        },
      },
      {
        field: 'qualification_score',
        label: 'Qualificação',
        criteria: {
          0: 'nenhuma',
          1: 'quase inexistente',
          2: 'intuitiva',
          3: 'critérios básicos',
          4: 'bem estruturada',
          5: 'clara, consistente e ligada ao ICP',
        },
      },
      {
        field: 'value_presentation_score',
        label: 'Apresentação de valor',
        criteria: {
          0: 'apenas preço',
          1: 'predominantemente entregáveis',
          2: 'valor pouco claro',
          3: 'boa apresentação',
          4: 'forte conexão problema-solução',
          5: 'valor altamente claro e personalizado ao contexto do lead',
        },
      },
      {
        field: 'objection_management_score',
        label: 'Tratamento de objeções',
        criteria: {
          0: 'ignoradas',
          1: 'reação improvisada',
          2: 'pouco estruturado',
          3: 'conhece principais objeções',
          4: 'responde com clareza',
          5: 'processo preventivo e baseado nas causas reais',
        },
      },
      {
        field: 'followup_score',
        label: 'Follow-up',
        criteria: {
          0: 'inexistente',
          1: 'raríssimo',
          2: 'irregular',
          3: 'básico',
          4: 'consistente',
          5: 'organizado, contextual e acompanhado',
        },
      },
      {
        field: 'lead_organization_score',
        label: 'Organização dos leads',
        criteria: {
          0: 'nenhum controle',
          1: 'conversas dispersas',
          2: 'controle manual frágil',
          3: 'organização funcional',
          4: 'sistema estruturado',
          5: 'CRM e acompanhamento consistente',
        },
      },
      {
        field: 'conversion_score',
        label: 'Conversão',
        criteria: {
          0: 'praticamente inexistente',
          1: 'muito baixa',
          2: 'baixa',
          3: 'funcional',
          4: 'boa',
          5: 'forte para o contexto',
        },
        note: 'Não defina a nota apenas pela porcentagem bruta — considere volume e contexto do negócio.',
      },
      {
        field: 'sales_data_quality_score',
        label: 'Qualidade dos dados comerciais',
        criteria: {
          0: 'nenhum dado',
          1: 'não sabe volume/conversão',
          2: 'estimativas frágeis',
          3: 'acompanha parcialmente',
          4: 'dados consistentes',
          5: 'acompanha etapas e taxas do processo',
        },
      },
    ],
  },

  operations: {
    name: 'Operação e Entrega',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'delivery_journey_score',
        label: 'Clareza da jornada',
        criteria: {
          0: 'nenhuma estrutura',
          1: 'totalmente improvisada',
          2: 'algumas etapas reconhecidas',
          3: 'jornada básica',
          4: 'jornada clara',
          5: 'jornada estruturada e continuamente melhorada',
        },
      },
      {
        field: 'process_standardization_score',
        label: 'Padronização',
        criteria: {
          0: 'nenhum processo',
          1: 'tudo depende da memória',
          2: 'materiais dispersos',
          3: 'alguns processos',
          4: 'maioria padronizada',
          5: 'processos essenciais documentados e utilizados',
        },
      },
      {
        field: 'operational_efficiency_score',
        label: 'Eficiência operacional',
        criteria: {
          0: 'grande desperdício',
          1: 'muito retrabalho',
          2: 'operação pesada',
          3: 'funcional',
          4: 'eficiente',
          5: 'altamente eficiente',
        },
      },
      {
        field: 'operational_independence_score',
        label: 'Independência operacional',
        criteria: {
          0: 'tudo depende do proprietário',
          1: 'quase tudo',
          2: 'grande parte',
          3: 'dependência moderada',
          4: 'pouca dependência operacional',
          5: 'operação estruturada sem participação constante em tarefas não estratégicas',
        },
      },
      {
        field: 'rework_control_score',
        label: 'Controle de retrabalho',
        criteria: {
          0: 'recorrente e crítico',
          1: 'muito frequente',
          2: 'relevante',
          3: 'moderado',
          4: 'baixo',
          5: 'processos evitam grande parte do retrabalho',
        },
      },
      {
        field: 'scaling_capacity_score',
        label: 'Capacidade de crescimento',
        criteria: {
          0: 'incapaz de crescer',
          1: 'crescimento geraria colapso',
          2: 'pouca capacidade',
          3: 'crescimento moderado possível',
          4: 'preparado',
          5: 'estrutura claramente escalável dentro do modelo atual',
        },
      },
    ],
  },

  ai: {
    name: 'Inteligência Artificial',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'ai_maturity_score',
        label: 'Maturidade de uso',
        criteria: {
          0: 'não utiliza',
          1: 'experimentação básica',
          2: 'tarefas isoladas',
          3: 'uso recorrente',
          4: 'IA integrada a vários processos',
          5: 'sistema de IA estruturado e orientado por funções',
        },
      },
      {
        field: 'ai_personalization_score',
        label: 'Personalização',
        criteria: {
          0: 'nenhum contexto',
          1: 'prompts genéricos',
          2: 'algumas instruções',
          3: 'contexto reutilizável',
          4: 'contexto estruturado',
          5: 'Cérebro Digital/arquitetura contextual integrada',
        },
      },
      {
        field: 'ai_process_integration_score',
        label: 'Integração com processos',
        criteria: {
          0: 'nenhuma',
          1: 'uso desconectado',
          2: 'apoio informal',
          3: 'integrada a algumas rotinas',
          4: 'integrada a processos importantes',
          5: 'IA opera dentro de sistema claramente definido',
        },
      },
      {
        field: 'ai_operational_gain_score',
        label: 'Potencial de ganho operacional',
        criteria: {
          0: 'nenhum ganho claro',
          1: 'baixo',
          2: 'limitado',
          3: 'relevante',
          4: 'alto',
          5: 'ganho significativo de tempo/capacidade/qualidade',
        },
      },
      {
        field: 'ai_application_clarity_score',
        label: 'Clareza de aplicação',
        criteria: {
          0: '"quero usar IA" sem objetivo',
          1: 'muito vaga',
          2: 'algumas ideias',
          3: 'tarefas identificadas',
          4: 'funções claras',
          5: 'trabalhos específicos, priorizados e mensuráveis',
        },
      },
      {
        field: 'ai_governance_score',
        label: 'Governança e segurança',
        criteria: {
          0: 'nenhum critério',
          1: 'uso sem revisão',
          2: 'revisão irregular',
          3: 'critérios básicos',
          4: 'revisão e limites definidos',
          5: 'governança clara por tipo de tarefa e risco',
        },
      },
    ],
  },

  automation: {
    name: 'Automação',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'automation_maturity_score',
        label: 'Maturidade de automação',
        criteria: {
          0: 'nenhuma automação',
          1: 'experiências isoladas',
          2: 'poucas automações',
          3: 'algumas rotinas funcionando',
          4: 'automações relevantes integradas',
          5: 'sistema estruturado e monitorado',
        },
      },
      {
        field: 'system_integration_score',
        label: 'Integração das ferramentas',
        criteria: {
          0: 'ferramentas totalmente isoladas',
          1: 'grande fragmentação',
          2: 'algumas conexões manuais',
          3: 'integração parcial',
          4: 'boa integração',
          5: 'sistemas importantes conectados',
        },
      },
      {
        field: 'repetitive_work_score',
        label: 'Volume de trabalho repetitivo (mede eficiência)',
        criteria: {
          0: 'enorme volume manual',
          1: 'muito alto',
          2: 'alto',
          3: 'moderado',
          4: 'baixo',
          5: 'tarefas repetitivas bem tratadas',
        },
      },
      {
        field: 'operational_automation_efficiency_score',
        label: 'Eficiência operacional',
        criteria: {
          0: 'muitos processos manuais e retrabalho',
          1: 'muito baixa',
          2: 'baixa',
          3: 'funcional',
          4: 'eficiente',
          5: 'altamente eficiente',
        },
      },
      {
        field: 'automation_safety_score',
        label: 'Segurança e supervisão',
        criteria: {
          0: 'automações sem controle',
          1: 'alto risco',
          2: 'controles insuficientes',
          3: 'supervisão básica',
          4: 'critérios claros',
          5: 'aprovação, logs e limites adequados ao risco',
        },
      },
      {
        field: 'automation_gain_potential_score',
        label: 'Potencial de ganho',
        criteria: {
          0: 'automação traria pouco benefício',
          1: 'baixo',
          2: 'moderado',
          3: 'relevante',
          4: 'alto',
          5: 'muito alto',
        },
      },
    ],
  },

  ethics: {
    name: 'Ética e Comunicação Profissional',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'professional_rules_knowledge_score',
        label: 'Conhecimento das normas',
        criteria: {
          0: 'desconhecimento quase total',
          1: 'conhecimento muito baixo',
          2: 'parcial',
          3: 'conhece regras principais',
          4: 'bom conhecimento',
          5: 'conhecimento atualizado e fontes organizadas',
        },
      },
      {
        field: 'ethics_review_process_score',
        label: 'Processo de revisão',
        criteria: {
          0: 'nenhum processo',
          1: 'revisão improvisada',
          2: 'baseada principalmente em memória',
          3: 'utiliza algumas fontes confiáveis',
          4: 'processo estruturado',
          5: 'protocolo claro + escalonamento quando necessário',
        },
      },
      {
        field: 'communication_safety_score',
        label: 'Segurança de comunicação',
        criteria: {
          0: 'alta exposição sem critérios',
          1: 'muito frágil',
          2: 'insegurança relevante',
          3: 'estrutura básica',
          4: 'boa segurança operacional',
          5: 'critérios claros e revisão adequada ao risco',
        },
      },
      {
        field: 'risk_exposure_control_score',
        label: 'Controle de exposição',
        criteria: {
          0: 'nenhum controle',
          1: 'alto risco',
          2: 'controles insuficientes',
          3: 'controles básicos',
          4: 'bom controle',
          5: 'comunicação sensível claramente identificada e revisada',
        },
      },
      {
        field: 'ethical_confidence_score',
        label: 'Confiança ética (capacidade de comunicar sem exposição imprudente nem bloqueio excessivo)',
        criteria: {
          0: 'comunicação paralisada ou exposição sem consciência',
          1: 'muito desequilibrada',
          2: 'insegurança relevante',
          3: 'equilíbrio básico',
          4: 'boa confiança com critérios',
          5: 'comunicação segura, consciente e funcional',
        },
        note: 'Não premie "não ter medo" — o que importa é equilíbrio entre segurança e exposição consciente.',
      },
      {
        field: 'ethics_support_structure_score',
        label: 'Estrutura de suporte',
        criteria: {
          0: 'nenhuma',
          1: 'depende apenas de memória/IA',
          2: 'recursos dispersos',
          3: 'algumas referências',
          4: 'checklist/base organizada',
          5: 'protocolo + fontes + revisão + escalonamento',
        },
      },
    ],
  },

  retention: {
    name: 'Experiência, Retenção e Renovação',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'customer_experience_score',
        label: 'Experiência do cliente',
        criteria: {
          0: 'experiência desestruturada',
          1: 'muitos pontos de ruptura',
          2: 'experiência pouco consistente',
          3: 'funcional',
          4: 'bem estruturada',
          5: 'experiência clara, acompanhada e melhorada',
        },
      },
      {
        field: 'value_tracking_score',
        label: 'Monitoramento de valor',
        criteria: {
          0: 'nenhum acompanhamento',
          1: 'percebe apenas problemas',
          2: 'feedback ocasional',
          3: 'acompanhamento básico',
          4: 'valor e satisfação acompanhados',
          5: 'percepção de valor integrada à jornada',
        },
      },
      {
        field: 'retention_score',
        label: 'Retenção',
        criteria: {
          0: 'não sabe por que clientes permanecem ou saem',
          1: 'muito baixa visibilidade',
          2: 'percepção informal',
          3: 'motivos parcialmente conhecidos',
          4: 'retenção acompanhada',
          5: 'causas compreendidas e utilizadas para melhoria',
        },
      },
      {
        field: 'renewal_score',
        label: 'Renovação',
        criteria: {
          0: 'nenhuma estrutura quando deveria existir',
          1: 'totalmente passiva',
          2: 'pouco estruturada',
          3: 'funcional',
          4: 'processo claro',
          5: 'renovação baseada em necessidade, valor e acompanhamento',
        },
      },
      {
        field: 'continuity_score',
        label: 'Continuidade',
        criteria: {
          0: 'nenhuma necessidade posterior',
          1: 'tentativa artificial',
          2: 'oportunidade incerta',
          3: 'próxima necessidade identificável',
          4: 'continuidade clara',
          5: 'jornada de continuidade estruturada',
        },
      },
      {
        field: 'referral_score',
        label: 'Indicação',
        criteria: {
          0: 'nenhuma indicação',
          1: 'muito baixa',
          2: 'somente espontânea',
          3: 'ocorre com frequência razoável',
          4: 'processo consciente',
          5: 'indicação integrada à experiência de forma adequada ao contexto profissional',
        },
      },
      {
        field: 'post_purchase_data_score',
        label: 'Dados pós-compra',
        criteria: {
          0: 'nenhum dado',
          1: 'quase nenhum',
          2: 'dados dispersos',
          3: 'alguns indicadores',
          4: 'boa visibilidade',
          5: 'métricas pós-compra apoiam decisões',
        },
      },
    ],
  },

  metrics: {
    name: 'Gestão, Métricas e Tomada de Decisão',
    formula: 'sum(available_scores) / count(available_scores)',
    dimensions: [
      {
        field: 'data_quality_score',
        label: 'Qualidade dos dados',
        criteria: {
          0: 'nenhum dado confiável',
          1: 'dados muito incompletos',
          2: 'estimativas e informações dispersas',
          3: 'dados básicos disponíveis',
          4: 'dados consistentes',
          5: 'dados confiáveis e utilizados para decisão',
        },
      },
      {
        field: 'metric_clarity_score',
        label: 'Clareza dos indicadores',
        criteria: {
          0: 'não sabe o que medir',
          1: 'mede apenas números aleatórios',
          2: 'alguns indicadores sem direção',
          3: 'principais indicadores conhecidos',
          4: 'indicadores ligados aos objetivos',
          5: 'poucos indicadores claros orientam decisões',
        },
      },
      {
        field: 'analysis_frequency_score',
        label: 'Frequência de análise',
        criteria: {
          0: 'nunca analisa',
          1: 'apenas quando há problema',
          2: 'irregular',
          3: 'análise periódica',
          4: 'boa cadência',
          5: 'cadência estruturada e adequada a cada indicador',
        },
      },
      {
        field: 'data_interpretation_score',
        label: 'Capacidade de interpretação',
        criteria: {
          0: 'não sabe interpretar',
          1: 'muita dificuldade',
          2: 'interpreta parcialmente',
          3: 'interpretação funcional',
          4: 'boa capacidade',
          5: 'consegue transformar informação em decisão',
        },
      },
      {
        field: 'decision_making_score',
        label: 'Tomada de decisão',
        criteria: {
          0: 'totalmente reativa',
          1: 'guiada por urgência',
          2: 'pouco estruturada',
          3: 'mistura dados e experiência',
          4: 'decisões orientadas por evidências',
          5: 'decisão + execução + revisão estruturadas',
        },
      },
      {
        field: 'data_integration_score',
        label: 'Integração das informações',
        criteria: {
          0: 'informações totalmente dispersas',
          1: 'grande fragmentação',
          2: 'várias fontes sem conexão',
          3: 'organização parcial',
          4: 'boa integração',
          5: 'visão consolidada do negócio',
        },
      },
    ],
  },
};

module.exports = { SCORE_RUBRICS };
